# file1=open("name.txt","w")
# file1.write("i am khushi awasthi\n")
# file1.write("i am ........")
# # print(file1.read())
# t=["\nPSIT","\nPSITCHE\n"]
# file1.writelines(t)
# myfile=open("file1.txt","r")
# print(myfile.readline())
# print(file1.readline())
# file1.close()

# myfile=open("myfile.txt","w")
# myfile.write("hello")
# t=["\nPSIT","\nPSITCHE\n"]
# myfile.writelines(t)
# myfile=open("myfile.txt","r")
# list1=myfile.readlines()
# print(list1)
# myfile.close()
# filep=open("filep.txt","w")
# t=("line","\n line1","\n line2","\n line3","\n line4","\n line5","\n line6")
# filep.writelines(t)
# filep=open("filep.txt","r")
# r=(filep.readlines())
# # p=int(input("enter the number:"))
# # print(r[p:])
# # to copy content from one file to another.
# myfile=open("myfile.txt","w")
# myfile.writelines(r)
# myfile=open("myfile.txt","r")
# print(myfile.readlines())
# filep.close()
###########################
# file1=open("file1.txt","w")
# t=("i am khushi\n","she is kashish\n")

# file1.writelines(t)
# print(file1.tell())
# print(file1.seek(13))
# file1=open("file1.txt","r")
# r=(file1.read())
# list=r.split()
# print("number of word in given file",len(list))
# file2=open("file1.txt","a")        
with open("mca.txt","w") as file:
    file.write("Kashish")